filegroup(
    name = "js",
    srcs = ["js.build_defs"],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "yarn_to_please",
    main = "yarn_to_please.py",
)

sh_binary(
    name = "yarn_binary",
    main = "yarn_binary.sh",
)
